spring:
  mail:
    # 163??????smtp.163.com???????
    host: smtp.163.com
    # ????163??
    username: royster61@163.com
    # ????????smtp/pop3?????????????????????
    password: SOZUOHNHSELFISQR
  datasource:
    url: jdbc:mysql://localhost:3306/study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
